services:
  crew:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/emilienmottet/crew-coach:latest
    env_file:
      - .env
    ports:
      - "49200:8000"
    stdin_open: true
    tty: true
    networks:
      - crew_net

networks:
  crew_net:
    external: true
